* Workspaces

Workspace -- это росовский термин используемый для обозначения локации, где вы разрабатываете на РОС.

Ядро ROS2, тоже является неким Workspace, которое называется "underlay" (или подложка). А другие локальные workspace
называется overlay (надложка).

Комбинирование workspace, может позволить использование разных версий
РОС, разные пакеты и т.п..  Это позволяет установку различных РОС на один компьютер и перемещаться между ними.
В итоге мы получаем что-то вроде окружения в python.

Для того чтобы команды РОС работали необходимо использовать команду

#+begin_src shell
source /opt/ros/humble/setup.bash
#+end_src

Можно также добавить это в =~/.bashrc= для работы РОС при перезапуске.

** Проверка переменных среды

С помощью команды ниже можно проверить переменные среды РОС и узнать их значение.

#+begin_src shell
printenv | grep -i ROS
#+end_src

Должны получится данные значения:

#+begin_src text
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_DISTRO=humble
#+end_src


В таблице ниже будут представлены переменные среды и их описание.

#+caption: Переменные среды РОСа
| Переменная         | Значение                                                                                                    |
|--------------------+-------------------------------------------------------------------------------------------------------------|
| ROS_DOMAIN_ID      | Уникальный идентификатор для группы нодов в РОС, уникальный и может быть выставлен по умолчанию в ~/.bashrc |
| ROS_LOCALHOST_ONLY | Работа роса будет только в пределах LOCALHOST                                                               |
